#cloud-config
datasource_list: [None]
timezone: Asia/Shanghai
disable_root: false
ssh_pwauth: true
users:
  - name: root
    lock_passwd: false
chpasswd:
  expire: false
  # 20.04 arm 需要
  list: |
    root:$6$0esRbIJ4LM5uA.CL$HD.A0m2f6lFwVVCcgu.7TZsWnuVeffSY3jrBz2tQEQaeQQvqfeBS7t4sefKIWCSpONXYBPMLgYTvMuzAB93Bl.
  users:
    - name: root
      password: $6$0esRbIJ4LM5uA.CL$HD.A0m2f6lFwVVCcgu.7TZsWnuVeffSY3jrBz2tQEQaeQQvqfeBS7t4sefKIWCSpONXYBPMLgYTvMuzAB93Bl.
      type: sha-512
runcmd:
  # opensuse tumbleweed 有 /etc/ssh/sshd_config.d/ 文件夹，没有 /etc/ssh/sshd_config，有/usr/etc/ssh/sshd_config
  - grep 'Include.*/etc/ssh/sshd_config.d' /etc/ssh/sshd_config && mkdir -p /etc/ssh/sshd_config.d && echo "PermitRootLogin yes" >/etc/ssh/sshd_config.d/01-permitrootlogin.conf || echo "PermitRootLogin yes" >>/etc/ssh/sshd_config
  - systemctl restart sshd
  - touch /etc/cloud/cloud-init.disabled
  # ubuntu 镜像运行 echo -e '\nDone' ，-e 会被显示出来
  - printf '\n%s\n' 'reinstall done' >/dev/tty0 || true
